package com.example.springjpa.many_to_one.two_way;

import com.example.springjpa.many_to_one.Member;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;

/**
 * Dog(N) <-> Member(N)
 *
 *     create table dog (
 *        dog_id bigint generated by default as identity,
 *         name varchar(255),
 *         member_id bigint,
 *         primary key (dog_id)
 *     )
 */

@Getter
@Setter
@ToString
@Entity
public class Dog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "dog_id")
    private Long id;

    @Column(name = "name")
    private String name;

    @ManyToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "member_id")
    private Member member;
}
