package com.example.springjpa.many_to_one.two_way;

import com.example.springjpa.many_to_one.School;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;

/**
 * Teacher(N) <-> School(1)
 *
 *     create table teacher (
 *        teacher_id bigint generated by default as identity,
 *         name varchar(255),
 *         school_id bigint,
 *         primary key (teacher_id)
 *     )
 */

@Getter
@Setter
@ToString
@Entity
public class Teacher {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "teacher_id")
    private Long id;

    @Column(name = "name")
    private String name;

    @ManyToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "school_id")
    private School school;
}
