package com.example.springjpa.one_to_one.one_way;

import com.example.springjpa.one_to_one.Person;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;

/**
 * Company(1) -> Person(1)
 *
 * create table company (
 *     company_id bigint generated by default as identity,
 *     name varchar(255),
 *     person_id bigint,
 *     primary key (company_id)
 * )
 *
 */

@Getter
@Setter
@Entity
public class Company {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "company_id")
    private Long id;

    @Column(name = "name")
    private String name;

    @OneToOne(cascade = CascadeType.PERSIST)
    @JoinColumn(name = "person_id")
    private Person person;
}
