package com.example.springjpa.many_to_one;

import com.example.springjpa.many_to_one.two_way.Dog;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 *     create table member (
 *        member_id bigint generated by default as identity,
 *         name varchar(255),
 *         primary key (member_id)
 *     )
 */

@Getter
@Setter
@ToString(exclude = "dogs")
@Entity
public class Member {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "member_id")
    private Long id;

    @Column(name = "name")
    private String name;

    @OneToMany(mappedBy = "member")
    private List<Dog> dogs = new ArrayList<>();
}
