package com.example.springjpa.many_to_one;

import com.example.springjpa.many_to_one.two_way.Teacher;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 *     create table school (
 *        school_id bigint generated by default as identity,
 *         primary key (school_id)
 *     )
 */

@Getter
@Setter
@ToString(exclude = "teachers")
@Entity
public class School {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "school_id")
    private Long id;

    @OneToMany(mappedBy = "school", cascade = CascadeType.ALL)
    private List<Teacher> teachers = new ArrayList<>();
}
